# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c434952c8a11a2c54d51256d5a31d34144a1e8ef3325bfa9e99cc1ba64b7cf958e32be9b7ff21d7a5427de1e571976aec606021dcc87f86f659257bb5fd20176

test:
  secret_key_base: 16d399988ec166c21dff0b7dbe88fda310274e5759ae84ebcabca7f09ddd0edcd56467755cbb3b643e01e597fc7a7fb9c9e2aea2284a1381d4517d5d8ababdd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
